stages:
  prepare:
    cmd: python src/prepare.py data/raw data/prepared
    deps:
      - data/raw
      - src/prepare.py
    outs:
      - data/prepared

  train:
    cmd: python src/train.py --prepared data/prepared
    deps:
      - data/prepared
      - src/train.py
      - src/models
    outs:
      - mlruns

  optimize:
    cmd: python src/optimize.py
    deps:
      - data/prepared
      - config/config.yaml
      - config/model
      - config/hpo
      - src/optimize.py
    outs:
      - temp
