stages:
  prepare:
    cmd: python src/prepare.py data/raw data/prepared
    deps:
      - data/raw
      - src/prepare.py
    outs:
      - data/prepared

  train:
    cmd: python src/train.py --prepared data/prepared
    deps:
      - data/prepared
      - src/train.py
      - src/models
    outs:
      - mlruns
